/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Ticket;


import Entidades.Visita;
import java.awt.Graphics;
import java.awt.Graphics2D;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Jon
 */
public class TicketJon extends javax.swing.JInternalFrame {

    private Visita v = new Visita();
    
    public TicketJon(Visita visita) {
        initComponents();
        this.v = visita;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPimprimible = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LabelID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabelFechaHora = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LabelNombre = new javax.swing.JLabel();
        LabelTratamiento = new javax.swing.JLabel();
        LabelPrecioMedicamentos = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LabelPrecioTratamiento = new javax.swing.JLabel();
        LabelImporteTotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Ticket ID");

        LabelID.setText("id de visita");

        jLabel3.setText("Fecha y hora:");

        LabelFechaHora.setText("Aca seteamos fecha y hora");

        jLabel2.setText("Nombre cliente");

        jLabel4.setText("Tratamiento");

        jLabel5.setText("Precio medicamentos");

        jLabel6.setText("Precio Total");

        LabelNombre.setText("Aca seteamos nombre de cliente");

        LabelTratamiento.setText("Nombre de tratamiento");

        LabelPrecioMedicamentos.setText("Metodo que calcula el total de medicamentos");

        jLabel7.setText("Precio tratamiento");

        LabelPrecioTratamiento.setText("Ya sabes que setear =P");

        LabelImporteTotal.setText("ImporteTotal");

        javax.swing.GroupLayout jPimprimibleLayout = new javax.swing.GroupLayout(jPimprimible);
        jPimprimible.setLayout(jPimprimibleLayout);
        jPimprimibleLayout.setHorizontalGroup(
            jPimprimibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPimprimibleLayout.createSequentialGroup()
                .addGroup(jPimprimibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPimprimibleLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(LabelID))
                    .addGroup(jPimprimibleLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPimprimibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPimprimibleLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LabelNombre))
                            .addGroup(jPimprimibleLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(LabelFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPimprimibleLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(46, 46, 46)
                                .addComponent(LabelPrecioTratamiento))))
                    .addGroup(jPimprimibleLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)
                        .addGap(41, 41, 41)
                        .addComponent(LabelTratamiento))
                    .addGroup(jPimprimibleLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6)
                        .addGap(71, 71, 71)
                        .addComponent(LabelImporteTotal))
                    .addGroup(jPimprimibleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelPrecioMedicamentos)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPimprimibleLayout.setVerticalGroup(
            jPimprimibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPimprimibleLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPimprimibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LabelID))
                .addGap(18, 18, 18)
                .addGroup(jPimprimibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LabelFechaHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPimprimibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LabelNombre))
                .addGap(18, 18, 18)
                .addGroup(jPimprimibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LabelTratamiento))
                .addGap(31, 31, 31)
                .addGroup(jPimprimibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(LabelPrecioTratamiento))
                .addGap(30, 30, 30)
                .addGroup(jPimprimibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(LabelPrecioMedicamentos))
                .addGroup(jPimprimibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPimprimibleLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6))
                    .addGroup(jPimprimibleLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LabelImporteTotal)))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPimprimible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPimprimible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(0, 96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try{
            PrinterJob pj = PrinterJob.getPrinterJob();
            pj.setPrintable((Printable) this);
            
            boolean top = pj.printDialog();
            
            if(top){
                pj.print();
            }
            
        }catch(PrinterException pe){
            JOptionPane.showMessageDialog(null, "Error de Impresion" + pe + JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFechaHora;
    private javax.swing.JLabel LabelID;
    private javax.swing.JLabel LabelImporteTotal;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelPrecioMedicamentos;
    private javax.swing.JLabel LabelPrecioTratamiento;
    private javax.swing.JLabel LabelTratamiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPimprimible;
    // End of variables declaration//GEN-END:variables

public void generarDatos(){
   double precioMed = v.getTratamiento().totalMedicamento();
    LabelPrecioMedicamentos.setText(precioMed + "");
    
    LabelTratamiento.setText(""+ v.getTratamiento().getPrecio());
    
    LabelID.setText(v.getIdVisita() + "");
    //LabelNombre.setText(v.get)
    
    
}


    public int print(Graphics graf, PageFormat pageFor, int index) throws PrinterException {
        
        if(index>0){
            return NO_SUCH_PAGE;
            
        }
        Graphics2D g = (Graphics2D)graf;
        g.translate(pageFor.getImageableX() , pageFor.getImageableY() );
        g.scale(0.7, 0.7);
        
        jPimprimible.printAll(graf);
        
        return PAGE_EXISTS;
       
    }
}
